web01 ansible_host= IP
web02 ansible_host= IP
db01 ansible_host= IP

[websrvgrp]
web01
web02

[dbsrvgrp]
db01

[web_db:children]
websrvgrp
dbsrvgrp

[web_db:vars]
ansible_user=centos
ansible_ssh_private_key_file=simple-web-deploy.pem